sudo: required
services:
  - docker

before_install:
  - docker build -t example-app -f Dockerfile.dev .

script:
  - docker run -e CI=true example-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "example-app"
  env: "ExampleApp-env"
  bucket_name: "elasticbeanstalk-eu-west-2-689346671119"
  bucket_path: "example-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY